# Generated by Django 5.2 on 2026-01-20 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_paciente', models.EmailField(max_length=254, unique=True)),
                ('password_paciente', models.CharField(max_length=128)),
                ('rut_paciente', models.CharField(max_length=9, unique=True)),
                ('nombre_paciente', models.CharField(max_length=50)),
                ('apellido_paciente', models.CharField(max_length=50)),
                ('fecha_nacimiento_paciente', models.DateField()),
                ('residencia_paciente', models.CharField(max_length=100)),
                ('telefono_paciente', models.CharField(max_length=15)),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.genero')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_medico', models.EmailField(max_length=254, unique=True)),
                ('password_medico', models.CharField(max_length=128)),
                ('rut_medico', models.CharField(max_length=9, unique=True)),
                ('nombre_medico', models.CharField(max_length=50)),
                ('apellido_medico', models.CharField(max_length=50)),
                ('especialidad_medico', models.CharField(max_length=50)),
                ('telefono_medico', models.CharField(max_length=15)),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.genero')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_administrativo', models.EmailField(max_length=254, unique=True)),
                ('password_administrativo', models.CharField(max_length=128)),
                ('rut_administrativo', models.CharField(max_length=9, unique=True)),
                ('nombre_administrativo', models.CharField(max_length=50)),
                ('apellido_administrativo', models.CharField(max_length=50)),
                ('telefono_administrativo', models.CharField(max_length=15)),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.genero')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
            options={
                'verbose_name': 'Administrativo',
                'verbose_name_plural': 'Administrativos',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_administrador', models.EmailField(max_length=254, unique=True)),
                ('password_administrador', models.CharField(max_length=128)),
                ('rut_administrador', models.CharField(max_length=9, unique=True)),
                ('nombre_administrador', models.CharField(max_length=50)),
                ('apellido_administrador', models.CharField(max_length=50)),
                ('telefono_administrador', models.CharField(max_length=15)),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.genero')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
    ]
