# Generated by Django 5.2 on 2026-01-20 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='especialidad_medico',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.especialidad'),
        ),
    ]
